### ISSUE TITLE
[Feature Request] SocialSply for msg/reply

### ISSUE THREAD

**Issue by hawkfalcon** [OskarsMC-Plugins/message#1]
To monitor for harassment, we need to make sure players aren't harassing other players via msg. 

Can you add a single permission which allows viewing of people's private messages?

**Comment by OskarZyg** [comment]
I think this as a permission as well as a command to enable/disable would be great, will work on it.

**Comment by OskarZyg** [comment]
I've made a PR, thoughts on it? If it's fine just comment that it's fine and I'll merge it.
