### ISSUE TITLE
Error executing commands

### ISSUE THREAD

**Issue by 4drian3d** [OskarsMC-Plugins/message#11]
When executing plugin commands in game/console, shows an error https://pastebin.com/zh7ZGKNt https://pastebin.com/L1Cn9g5h.

**Comment by 4drian3d** [comment]
Correction... I just connect from a client to test that the commands work correctly (I have been testing everything from the console), I get the same error when trying to execute the command, in the client nothing comes out, in the console the same error comes out.

**Comment by OskarZyg** [comment]
I've fixed this locally. I will test **all** the features of the plugin before releasing the next release. Sorry for the low-quality fixes recently, I haven't had a lot of time.
