### ISSUE TITLE
Java version required

### ISSUE THREAD

**Issue by 4drian3d** [OskarsMC-Plugins/message#13]
It would be good to specify the Java version required by the plugin somewhere (README or in the Velocity forum post)
As I see, it uses some functions of more recent versions of Java without indicating it https://github.com/OskarsMC-Plugins/message/blob/main/src/main/java/com/oskarsmc/message/util/DefaultPermission.java#L11 _The "record" specifically_

**Comment by OskarZyg** [comment]
Would something like
<hr>

## Technical Details
### Java
Recommended Version: 17
Tested Versions: 16, 17
<hr>

be alright?

**Comment by 4drian3d** [comment]
I think that would be fine
