### ISSUE TITLE
Problems w message (can we have discord link?)

### ISSUE THREAD

**Issue by jokbon** [OskarsMC-Plugins/message#14]
for some reason sudenly it started to ask for permision, meanwhile permisions are given in luckperms default group.
what it could be?

**Comment by jokbon** [comment]
when using op those are oweriden by essentials so cant realy test in that way unles u want me to remove essentials x)
but everything worked before fine until suden (i didnt do any changes just updated plugins)

**Comment by OskarZyg** [comment]
Message is a velocity plugin, velocity has no concept of op and doesn't support essx... could you send a `/velocity dump`?

The discord invite is https://discord.gg/KfmcRzv6Gh I'll add it to the README.md when I have time.

**Comment by OskarZyg** [comment]
Closing this issue until i get a response.
