### ISSUE TITLE
[Feature Request] Command /reply and more aliases

### ISSUE THREAD

**Issue by 4drian3d** [OskarsMC-Plugins/message#2]
It would be nice if the plugin could have a "/r" or "/reply" to quickly reply to the person who sent a message before. And if it were possible that there are more aliases for the command "/message" and "/msg" such as "/tell" or others, or add a section in configuration to add extra shortening.

**Comment by OskarZyg** [comment]
I'm not exactly sure how I should do aliases (was even confused here: https://github.com/OskarsMC-Network/message/blob/main/src/main/java/com/oskarsmc/message/command/MessageBrigadier.java#L88), as a temporary solution you can probably use an alias plugin, ill try to get aliases working and I will work on a /reply feature.

**Comment by 4drian3d** [comment]
> I'm not exactly sure how I should do aliases (was even confused here: https://github.com/OskarsMC-Network/message/blob/main/src/main/java/com/oskarsmc/message/command/MessageBrigadier.java#L88), as a temporary solution you can probably use an alias plugin, ill try to get aliases working and I will work on a /reply feature.

Exactly that I did at the time of reviewing the source, I only say it for others who use the plugin, since normally there are "/tell" and other aliases in plugin of this topic

**Comment by OskarZyg** [comment]
Thoughts on the alias feature?

**Comment by 4drian3d** [comment]
The aliases for the commands work correctly, it would be good if the plugin brings its own "/vmsg reload" for example, to avoid completely restarting Velocity when making a minimum change.

**Comment by OskarZyg** [comment]
Done.
