### ISSUE TITLE
Basic commands are not assigned by default

### ISSUE THREAD

**Issue by 4drian3d** [OskarsMC-Plugins/message#5]
When creating a new server, the basic command "/msg" is not assigned as default. It is required to have a permission plugin such as LuckPermsVelocity to just assign it, it would be ideal to give the command to the players as default to avoid this inconvenience to the new servers and in case someone does not want to use LuckPermsVelocity or another permission plugin to be able to use that command.

**Comment by OskarZyg** [comment]
Will work on it.
