### ISSUE TITLE
Error with plugin on player disconnection

### ISSUE THREAD

**Issue by 4drian3d** [OskarsMC-Plugins/message#8]
Some time ago I noticed that in the Velocity console some errors appear when the player exits the network, which seem to be somehow related to the plugin. The error is: https://pastebin.com/ajYyPHz1 (the player's name and ip were censored for security reasons).

**Comment by OskarZyg** [comment]
I'll look into it. Have you found a method to reproduce this?

**Comment by 4drian3d** [comment]
At the moment, no, it's still happening, I think it's because they disconnect right after having a conversation using the plugin. 
https://pastebin.com/EzstVMUu
My plugin list is 
03.05 15:13:23 ---------@gmail.com ran command: velocity plugins
03.05 15:13:23 [Server] INFO Plugins: commandwhitelist, epicguard, luckperms, message, minimotd-velocity, nuvotifier, skinsrestorer

**Comment by OskarZyg** [comment]
If you could test out the artifact of the linked PR and are happy it fixes the issue I will merge it and include it as part of 0.2.1.

**Comment by 4drian3d** [comment]
So far it hasn't given me any errors, so I think it's already fixed.

**Comment by 4drian3d** [comment]
At startup, I got the error https://pastebin.com/9ZnEGD5B.

**Comment by OskarZyg** [comment]
I'm aware of this, the latest commit fixes it. I'll release a 0.2.1 to fix that.

**Comment by OskarZyg** [comment]
In the meantime, you can grab https://github.com/OskarsMC-Plugins/message/actions/runs/810529293

**Comment by 4drian3d** [comment]
> In the meantime, you can grab https://github.com/OskarsMC-Plugins/message/actions/runs/810529293

I get the same error https://prnt.sc/12hhqjn

**Comment by OskarZyg** [comment]
Apologies, https://github.com/OskarsMC-Plugins/message/actions/runs/810737671 should fix (again)

**Comment by OskarZyg** [comment]
Sorry for the mess- https://github.com/OskarsMC-Plugins/message/actions/runs/810799555 should fix it.

**Comment by 4drian3d** [comment]
The latest version (compiled together with the changes of #9 ), starts correctly and seems to work fine.
